# Drone CI Pipeline for nbin

## AMD64 Pipeline - Build Test
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

steps:
- name: restore-cache
  image: codercom/drone-volume-cache:amd64
  volumes:
  - name: ccache-amd64
    path: /cache
  settings:
    restore: true
    mount:
      - /root/.cache/ccache

- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - TARGET=amd64 ./scripts/ci.bash

- name: rebuild-cache
  image: codercom/drone-volume-cache:amd64
  volumes:
  - name: ccache-amd64
    path: /cache
  settings:
    rebuild: true
    mount:
      - /root/.cache/ccache

trigger:
  event:
    exclude:
    - tag

---
## ARM64 - Build Test
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

steps:
- name: restore-cache
  image: codercom/drone-volume-cache:arm64
  volumes:
  - name: ccache-arm64
    path: /cache
  settings:
    restore: true
    mount:
      - /root/.cache/ccache

- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - TARGET=arm64 ./scripts/ci.bash

- name: rebuild-cache
  image: codercom/drone-volume-cache:arm64
  volumes:
  - name: ccache-arm64
    path: /cache
  settings:
    rebuild: true
    mount:
      - /root/.cache/ccache

trigger:
  event:
    exclude:
    - tag

---
## ARM - Build Test
kind: pipeline
type: docker
name: build-arm

platform:
  arch: arm

steps:
- name: restore-cache
  image: codercom/drone-volume-cache:arm
  volumes:
  - name: ccache-arm
    path: /cache
  settings:
    restore: true
    mount:
      - /root/.cache/ccache

- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - TARGET=arm ./scripts/ci.bash

- name: rebuild-cache
  image: codercom/drone-volume-cache:arm
  volumes:
  - name: ccache-arm
    path: /cache
  settings:
    rebuild: true
    mount:
      - /root/.cache/ccache

trigger:
  event:
    exclude:
    - tag

---
## AMD64 - Release
kind: pipeline
type: docker
name: release-amd64

platform:
  arch: amd64

steps:
- name: restore-cache
  image: codercom/drone-volume-cache:amd64
  volumes:
  - name: ccache-amd64
    path: /cache
  settings:
    restore: true
    mount:
      - /root/.cache/ccache

- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - TARGET=amd64 ./scripts/ci.bash

- name: deploy
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token

trigger:
  event:
  - tag

---
## ARM64 - Release
kind: pipeline
type: docker
name: release-arm64

platform:
  arch: arm64

steps:
- name: restore-cache
  image: codercom/drone-volume-cache:arm64
  volumes:
  - name: ccache-arm64
    path: /cache
  settings:
    restore: true
    mount:
      - /root/.cache/ccache

- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - TARGET=arm64 ./scripts/ci.bash

- name: deploy
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token

trigger:
  event:
  - tag

---
## ARM - Release
kind: pipeline
type: docker
name: release-arm

platform:
  arch: arm

steps:
- name: restore-cache
  image: codercom/drone-volume-cache:arm
  volumes:
  - name: ccache-arm
    path: /cache
  settings:
    restore: true
    mount:
      - /root/.cache/ccache

- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - TARGET=arm ./scripts/ci.bash

- name: deploy
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token

trigger:
  event:
  - tag
