kind: pipeline
type: docker
name: amd64:linux

platform:
  arch: amd64

steps:
- name: build
  image: node:12
  environment:
    CLOUDSDK_CORE_PROJECT: coder-production
    KEY_FILE_CONTENTS:
      from_secret: gcs-json-key-file-base64
  commands:
    - apt update && apt install -y build-essential ccache python-pip
    - yarn
    - pip install gsutil
    - ./scripts/cache.bash restore .cache ${DRONE_BRANCH}
    - ./scripts/ci.bash
    - ./scripts/cache.bash rebuild .cache ${DRONE_BRANCH}

- name: test
  image: node:12
  commands:
    - yarn test

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: amd64:alpine

platform:
  arch: amd64

steps:
- name: build
  image: node:12-alpine
  environment:
    CLOUDSDK_CORE_PROJECT: coder-production
    KEY_FILE_CONTENTS:
      from_secret: gcs-json-key-file-base64
  commands:
    - apk add bash gcc g++ ccache git make python linux-headers py-pip python-dev openssl-dev libffi-dev
    - yarn
    - pip install gsutil
    - ./scripts/cache.bash restore .cache ${DRONE_BRANCH}
    - ./scripts/ci.bash
    - ./scripts/cache.bash rebuild .cache ${DRONE_BRANCH}

- name: test
  image: node:12-alpine
  commands:
    - yarn test

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm64:linux

platform:
  arch: arm64

steps:
- name: build
  image: node:12
  environment:
    CLOUDSDK_CORE_PROJECT: coder-production
    KEY_FILE_CONTENTS:
      from_secret: gcs-json-key-file-base64
  commands:
    - apt update && apt install -y build-essential ccache python-pip
    - yarn
    - pip install gsutil
    - ./scripts/cache.bash restore .cache ${DRONE_BRANCH}
    - ./scripts/ci.bash
    - ./scripts/cache.bash rebuild .cache ${DRONE_BRANCH}

- name: test
  image: node:12
  commands:
    - yarn test

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm64:alpine

platform:
  arch: arm64

steps:
- name: build
  image: node:12-alpine
  environment:
    CLOUDSDK_CORE_PROJECT: coder-production
    KEY_FILE_CONTENTS:
      from_secret: gcs-json-key-file-base64
  commands:
    - apk add bash gcc g++ ccache git make python linux-headers py-pip python-dev openssl-dev libffi-dev
    - yarn
    - pip install gsutil
    - ./scripts/cache.bash restore .cache ${DRONE_BRANCH}
    - ./scripts/ci.bash
    - ./scripts/cache.bash rebuild .cache ${DRONE_BRANCH}

- name: test
  image: node:12-alpine
  commands:
    - yarn test

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm:linux

platform:
  arch: arm

steps:
- name: build
  image: node:12
  environment:
    CLOUDSDK_CORE_PROJECT: coder-production
    KEY_FILE_CONTENTS:
      from_secret: gcs-json-key-file-base64
  commands:
    - apt update && apt install -y build-essential ccache python-pip
    - yarn
    - pip install gsutil
    - ./scripts/cache.bash restore .cache ${DRONE_BRANCH}
    - ./scripts/ci.bash
    - ./scripts/cache.bash rebuild .cache ${DRONE_BRANCH}

- name: test
  image: node:12
  commands:
    - yarn test

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm:alpine

platform:
  arch: arm

steps:
- name: build
  image: node:12-alpine
  environment:
    CLOUDSDK_CORE_PROJECT: coder-production
    KEY_FILE_CONTENTS:
      from_secret: gcs-json-key-file-base64
  commands:
    - apk add bash gcc g++ ccache git make python linux-headers py-pip python-dev openssl-dev libffi-dev
    - yarn
    - pip install gsutil
    - ./scripts/cache.bash restore .cache ${DRONE_BRANCH}
    - ./scripts/ci.bash
    - ./scripts/cache.bash rebuild .cache ${DRONE_BRANCH}

- name: test
  image: node:12-alpine
  commands:
    - yarn test

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag
