kind: pipeline
type: docker
name: amd64:linux

platform:
  arch: amd64

steps:
- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - ./scripts/ci.bash

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: amd64:alpine

platform:
  arch: amd64

steps:
- name: build
  image: node:12-alpine
  commands:
    - apk add bash gcc g++ ccache git make python linux-headers
    - yarn
    - ./scripts/ci.bash

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm64:linux

platform:
  arch: arm64

steps:
- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - ./scripts/ci.bash

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm64:alpine

platform:
  arch: arm64

steps:
- name: build
  image: node:12-alpine
  commands:
    - apk add bash gcc g++ ccache git make python linux-headers
    - yarn
    - ./scripts/ci.bash

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm:linux

platform:
  arch: arm

steps:
- name: build
  image: node:12
  commands:
    - apt update && apt install -y build-essential ccache
    - yarn
    - ./scripts/ci.bash

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag

---
kind: pipeline
type: docker
name: arm:alpine

platform:
  arch: arm

steps:
- name: build
  image: node:12-alpine
  commands:
    - apk add bash gcc g++ ccache git make python linux-headers
    - yarn
    - ./scripts/ci.bash

- name: upload
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token
  when:
    event: tag
