language: node_js
node_js:
- 8.15.0
matrix:
  include:
  - os: linux
    dist: ubuntu
  - os: osx
jobs:
  include:
    - stage: build
      script: scripts/ci.sh
    - stage: test
      script: yarn test